version: '3'
services:
  eosio-cdt:
    image: eostudio/eosio.cdt:v1.7.0
    container_name: "eosio-cdt"
    volumes:
      - ./:/var/repo
  eosio:
    build:
      context: ./blockchain
      dockerfile: Dockerfile-eosio
    container_name: "eosio"
    ports:
      - 8888:8888
    volumes:
      - ./:/var/repo
      - ./temp/eosio:/data
  # mongo:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_DATA_DIR=/data
  #     - MONGO_LOG_DIR=/dev/null
  #     - MONGODB_USER="user" 
  #     - MONGODB_PASS="pass"
  #   volumes:
  #     - ./temp/mongo:/data
  #   command:
  #     sh -c 'mongod >> /data/mongod.log 2>&1'
  back-end:
    image: node
    container_name: "back-end"
    ports:
      - 4000:4000
    volumes:
     - ./:/var/repo
     - ./temp/back-end:/data
    working_dir: /var/repo/back-end
    command:
      sh -c 'npm start >> /data/nodejs.log 2>&1'
  front-end:
    image: node
    container_name: "front-end"
    ports:
      - 3000:3000
    volumes:
      - ./:/var/repo
      - ./temp/front-end:/data
    working_dir: /var/repo/front-end
    command:
      sh -c 'npm start >> /data/nodejs.log 2>&1'