version: '3'
services:
  # eosio:
  #   image: eostudio/eos:v2.0.3
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - ./:/var/repo
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user" 
      - MONGODB_PASS="pass"
    volumes:
      - ./temp:/data
  # back-end:
  #   image: node
  #   ports:
  #     - 3000
  #   volumes:
  #     - ./:~/repo