name: CD

on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: devops
      
      - name: Deploy to EC2 server
        env:
          EC2_PEM: ${{ secrets.EC2_PEM }}
        run: cd scripts/server && bash deploy_to_server.sh