name: CD

on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 server
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: cd scripts/server && bash travis_deploy.sh