name: CD

on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: devops
      
      - name: Deploy to EC2 server
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
          EC2_PEM: ${{ secrets.EC2_PEM }}
        run: |
          ls
          ls $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          cd scripts/server && bash travis_deploy.sh